import numpy as np

a = np.array([1, 2, 3, 4, 5])
l = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ddd = d.reshape(2, 4)
c = np.concatenate([a, d])
gp = a.copy()
lic = a.view()
a[0] = 6
rsp = a.reshape(5, 1)
b = l.reshape(5, 2)
top = np.array([[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]])
addText = np.concatenate([l, top], axis=1)
s = np.stack([a, lic], axis=1)
hs = np.hstack([a, lic])
vs = np.vstack([a, lic])
ds = np.dstack([a, lic])
spd = np.split(d, 2)
ts = np.split(top, 2)
hsp = np.hsplit(hs, 2)
vsp = np.vsplit(vs, 2)
dsp = np.dsplit(ds, 2)
print(gp)
print(lic)
print(gp.base)
print(lic.base)
print(a.shape)
print(l.shape)
print(rsp)
print(b)
print(ddd)
print(ddd.base)
for i in np.nditer(ddd):
    print(i)
for i, j in np.ndenumerate(ddd):
    print(i, j)
print(c)
print(addText)
print(s)
print(hs)
print(vs)
print(ds)
print(spd)
print(ts)
print(hsp)
print(vsp)
print(dsp)
